In [3]:
import pandas as pd
import altair as alt

In [9]:
df = pd.read_csv("../data/processed/data.csv")

In [10]:
def col_filter(cat_value):
    cols = ['city', 'data_quality','province', 'population']
    for i in cat_value:
        if i == 'restaurant':
            cols = cols + list(df.columns[2:10])
        if i == 'market':
            cols = cols + list(df.columns[10:29])
        if i == 'transportation':
            cols = cols + list(df.columns[29:37])
        if i == 'utilities':
            cols = cols + list(df.columns[37:40])
        if i == 'leisure':
            cols = cols + list(df.columns[40:43])
        if i == 'childcare':
            cols = cols + list(df.columns[43:45])
        if i == 'clothing':
            cols = cols + list(df.columns[45:49])
        if i == 'home':
            cols = cols + list(df.columns[49:57])
    return cols

In [6]:
df[col_filter(['restaurant'])]

,city,data_quality,lat,lng,province,population,meal_cheap,meal_mid,meal_mcd,r_beer_dom,r_beer_imp,r_cappuccino,r_coke,r_water
0,Toronto,1,43.7417,-79.3733,Ontario,2794356.0,18.53,85.23,9.63,5.19,6.36,3.59,1.95,1.53
1,Montreal,1,45.5089,-73.5617,Quebec,1762949.0,14.82,66.70,9.63,5.93,5.93,3.57,1.76,1.37
2,Vancouver,1,49.2500,-123.1000,British Columbia,662248.0,18.16,83.38,8.89,5.19,6.67,3.80,1.94,1.77
3,Calgary,1,51.0500,-114.0667,Alberta,1306784.0,18.53,63.00,8.89,5.19,5.93,3.75,1.75,1.53
4,Edmonton,1,53.5344,-113.4903,Alberta,1010899.0,18.53,66.70,8.89,5.19,5.93,3.79,1.82,1.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,Peace River,0,56.2339,-117.2897,Alberta,6619.0,14.08,42.62,8.15,5.56,6.30,4.29,1.82,1.86
116,Parry Sound,0,45.3333,-80.0333,Ontario,6879.0,NaN,NaN,8.89,5.93,5.93,3.15,2.41,1.67
117,La Ronge,0,55.1000,-105.3000,Saskatchewan,2521.0,NaN,37.06,8.89,4.45,4.82,2.22,1.85,1.48
118,Flin Flon,0,54.7667,-101.8778,Saskatchewan,5099.0,NaN,NaN,11.12,4.45,5.19,NaN,2.22,1.48
119,Iqaluit,0,63.7598,-68.5107,Nunavut,7429.0,29.65,74.27,13.71,6.67,8.89,3.71,3.52,4.08

In [11]:
dff = df[col_filter(['home'])]

In [22]:
dff

,city,data_quality,province,population,bed1_centre,bed1_out,bed3_centre,bed3_out,buy_centre,buy_out,salary,mortgage
0,Toronto,1,Ontario,2794356.0,1728.50,1426.71,2733.40,2302.11,9834.67,7249.17,3249.79,5.24
1,Montreal,1,Quebec,1762949.0,1045.58,800.16,1846.59,1342.69,6069.66,3487.84,2823.94,5.41
2,Vancouver,1,British Columbia,662248.0,1799.96,1502.80,3373.09,2341.43,9983.22,7902.75,3474.89,4.46
3,Calgary,1,Alberta,1306784.0,1121.71,903.12,1976.24,1504.96,3328.49,2651.05,3807.94,4.58
4,Edmonton,1,Alberta,1010899.0,906.92,745.74,1535.36,1153.16,2200.36,1841.51,3403.02,4.82
...,...,...,...,...,...,...,...,...,...,...,...,...
115,Peace River,0,Alberta,6619.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.47
116,Parry Sound,0,Ontario,6879.0,815.26,741.15,993.05,NaN,NaN,NaN,NaN,NaN
117,La Ronge,0,Saskatchewan,2521.0,592.92,592.92,741.15,741.15,NaN,NaN,NaN,2.64
118,Flin Flon,0,Saskatchewan,5099.0,NaN,589.21,NaN,NaN,NaN,NaN,NaN,NaN
119,Iqaluit,0,Nunavut,7429.0,NaN,NaN,2964.60,2964.60,NaN,NaN,NaN,6.53

In [8]:
new_names = pd.read_csv("../data/processed/data_new_names.csv", header = 0)
# df to list
old = new_names.old_name.values.tolist()
new  = new_names.new_name.values.tolist()
# lists to dictionary
new_name_dic = {}
for key in old:
    for value in new:
        new_name_dic[key] = value
        new.remove(value)
        break

In [12]:
[{'label': new_name_dic[col], 'value': col} for col in dff.columns[4:]]

[{'label': 'Apartment City (1 bed)', 'value': 'bed1_centre'},
 {'label': 'Apartment Outside (1 bed)', 'value': 'bed1_out'},
 {'label': 'Apartment City (3 bed)', 'value': 'bed3_centre'},
 {'label': 'Apartment Outside (3 bed)', 'value': 'bed3_out'},
 {'label': 'Apartment City (/sq m)', 'value': 'buy_centre'},
 {'label': 'Apartment Outside (/sq m)', 'value': 'buy_out'},
 {'label': 'Monthly Net Salary', 'value': 'salary'},
 {'label': 'Mortgage Interest Rate', 'value': 'mortgage'}]

In [38]:
dff.columns[4:]

Index(['bed1_centre', 'bed1_out', 'bed3_centre', 'bed3_out', 'buy_centre',
       'buy_out', 'salary', 'mortgage'],
      dtype='object')

In [46]:
prov_chosen = ['Alberta','Quebec']
population_chosen = [0, 2800000]
drop1_chosen = "meal_mid"
drop_b = ['Edmonton','Kelowna']
categories = ['market']

In [43]:
def plot_altair1(prov_chosen, population_chosen, drop1_chosen, drop_b, categories):
    # filtering df
    popmin = population_chosen[0]
    popmax = population_chosen[1]
    dff = df[df['population'].between(popmin, popmax)]
    dff = dff[col_filter(categories)] 
    dff = dff[dff['province'].isin(prov_chosen)]

    # setting filtered dropdown options
    prov_cities = [{'label': cities, 'value': cities} for cities in dff['city']]
    newoptions = [{'label': new_name_dic[col], 'value': col} for col in dff.columns[4:]]

    barchart = alt.Chart(dff[-pd.isnull(dff[drop1_chosen])]).mark_bar().encode(
    alt.X(drop1_chosen, title='Cost of '+drop1_chosen, axis=alt.Axis(orient='top',format='$.0f')),
    alt.Y('city', sort='x', title=""),
    color = alt.condition(alt.FieldOneOfPredicate(field='city', oneOf=drop_b),
                              alt.value('red'),
                              alt.value('steelblue')),
    tooltip=[drop1_chosen,'province']).configure_axis(labelFontSize = 16, titleFontSize=20)
    return barchart.to_html()

In [47]:
plot_altair1(prov_chosen, population_chosen, drop1_chosen, drop_b, categories)

KeyError: 'meal_mid'

In [45]:
popmin = population_chosen[0]
popmax = population_chosen[1]
dff = df[df['population'].between(popmin, popmax)]
dff = dff[col_filter(categories)] 
dff = dff[dff['province'].isin(prov_chosen)]
dff

,city,data_quality,province,population,milk_1L,bread_white,rice_1kg,eggs_doz,cheese_local_1kg,chicken_fillet_1kg,...,orange_1kg,tomato_1kg,potato_1kg,onion_1kg,lettuce,water_1.5L,winebottle_mid,beer_dom,beer_imp,cigarettes_20
1,Montreal,1,Quebec,1762949.0,2.17,2.81,2.90,2.87,11.40,11.07,...,3.11,3.47,1.84,1.96,2.08,1.68,11.86,2.40,2.69,11.12
3,Calgary,1,Alberta,1306784.0,1.73,2.18,2.57,2.90,10.88,10.51,...,3.51,3.78,2.21,2.62,2.42,1.63,11.12,2.55,2.86,11.86
4,Edmonton,1,Alberta,1010899.0,1.97,2.22,3.05,2.69,10.75,11.14,...,3.39,3.67,2.01,1.76,2.40,1.68,11.12,2.05,2.68,12.60
7,Quebec City,1,Quebec,549459.0,1.54,2.43,3.28,2.65,11.90,8.89,...,2.73,3.40,2.43,1.57,1.70,0.95,11.12,1.54,2.54,10.38
15,Laval,1,Quebec,438366.0,1.72,2.12,2.20,2.34,11.27,10.26,...,2.26,3.03,1.84,2.08,2.13,1.75,12.41,2.96,2.41,9.63
20,Gatineau,1,Quebec,291041.0,1.78,2.43,3.87,2.57,8.17,6.40,...,2.64,5.36,1.60,2.08,1.45,1.18,8.89,3.42,NaN,8.96
30,Sherbrooke,0,Quebec,172950.0,1.85,2.18,3.03,2.83,7.54,10.57,...,2.93,3.36,1.66,1.80,1.39,1.51,11.12,2.29,2.22,10.38
31,Saguenay,0,Quebec,144723.0,1.48,2.41,2.96,2.35,12.41,9.51,...,4.07,2.43,0.82,1.63,1.66,0.85,11.12,2.01,2.04,8.15
35,Trois-Rivieres,0,Quebec,139163.0,1.53,2.74,5.60,2.63,19.14,12.83,...,4.81,3.70,2.09,4.07,2.48,1.53,11.86,2.52,2.70,8.15
45,Red Deer,1,Alberta,100844.0,1.53,2.24,3.06,2.58,7.22,9.30,...,3.05,3.56,2.03,2.20,1.74,1.66,14.82,2.79,3.80,11.38
50,Lethbridge,1,Alberta,98406.0,1.51,2.53,5.87,3.74,16.28,9.79,...,4.31,4.78,2.18,4.08,2.82,2.11,11.12,2.59,3.77,12.04
61,Chateauguay,0,Quebec,50815.0,1.46,2.55,2.59,2.22,8.15,15.31,...,4.44,4.82,1.67,3.70,1.90,1.62,8.81,NaN,NaN,NaN
62,St. Albert,0,Alberta,68232.0,1.92,2.22,3.05,3.09,10.75,11.14,...,3.39,3.15,2.01,1.76,1.70,1.68,11.86,2.05,1.82,11.12
63,Granby,0,Quebec,69025.0,1.54,2.43,3.28,2.50,11.90,8.89,...,2.73,3.40,1.73,1.57,1.60,0.95,11.12,1.48,2.22,10.38
69,Rimouski,0,Quebec,48935.0,1.54,2.22,3.28,2.22,11.90,8.89,...,2.73,3.40,2.43,1.57,1.70,0.95,11.12,1.54,2.54,10.38
71,Victoriaville,0,Quebec,47760.0,1.48,2.04,1.88,2.22,NaN,3.71,...,2.22,2.22,0.74,0.67,0.93,1.11,11.12,3.71,1.48,5.93
74,Mascouche,0,Quebec,51183.0,1.48,1.48,3.71,2.22,19.14,6.67,...,1.48,2.96,2.96,1.48,2.22,1.53,11.86,2.52,1.48,8.15
75,Salaberry-de-Valleyfield,0,Quebec,42787.0,2.59,2.12,3.28,2.67,8.77,9.42,...,2.43,2.22,1.59,1.75,1.79,2.96,11.12,2.51,1.48,13.34
76,Rouyn-Noranda,0,Quebec,42313.0,1.76,2.64,3.31,2.59,11.72,8.95,...,4.00,4.08,2.75,2.00,1.73,1.24,11.12,2.97,2.87,8.89
81,Spruce Grove,0,Alberta,37645.0,2.33,1.57,4.07,3.01,NaN,14.82,...,3.70,NaN,1.85,NaN,2.20,NaN,6.67,NaN,NaN,NaN
88,Sept-Iles,0,Quebec,24569.0,2.19,3.00,6.98,3.26,12.08,15.56,...,6.54,4.59,2.43,2.84,2.33,2.22,15.56,NaN,NaN,NaN
91,Fort Saskatchewan,0,Alberta,27088.0,2.47,2.72,4.56,3.34,10.38,10.13,...,4.67,3.55,3.95,2.72,2.37,2.41,18.53,1.52,3.34,14.82
92,Baie-Comeau,0,Quebec,20687.0,1.42,2.47,10.38,3.89,13.70,16.22,...,11.16,6.52,5.15,5.07,4.44,2.93,23.68,NaN,NaN,18.53
97,Riviere-du-Loup,0,Quebec,20118.0,1.48,1.48,1.48,1.85,NaN,NaN,...,NaN,NaN,NaN,NaN,2.22,NaN,11.12,NaN,NaN,NaN
106,Canmore,0,Alberta,15990.0,2.03,2.71,5.04,3.23,11.86,14.48,...,3.87,5.50,3.43,3.96,2.59,2.27,13.34,2.96,3.71,12.23
114,Banff,0,Alberta,8305.0,2.03,2.56,5.04,3.42,12.59,14.48,...,5.26,5.49,4.21,3.96,3.49,3.59,13.34,3.04,3.86,14.82
115,Peace River,0,Alberta,6619.0,2.24,2.52,3.62,3.81,6.67,8.89,...,NaN,NaN,NaN,NaN,1.85,NaN,NaN,NaN,NaN,14.82

In [13]:
drop_options = [{'label': new_name_dic[col], 'value': col} for col in df.columns[2:57]]

In [15]:
type(drop_options[0])

dict

In [20]:
drop_options[1]['value']

'meal_mid'

In [22]:
col_filter(['restaurant','market'])[4:]

['meal_cheap',
 'meal_mid',
 'meal_mcd',
 'r_beer_dom',
 'r_beer_imp',
 'r_cappuccino',
 'r_coke',
 'r_water',
 'milk_1L',
 'bread_white',
 'rice_1kg',
 'eggs_doz',
 'cheese_local_1kg',
 'chicken_fillet_1kg',
 'beef_round_1kg',
 'apple_1kg',
 'banana_1kg',
 'orange_1kg',
 'tomato_1kg',
 'potato_1kg',
 'onion_1kg',
 'lettuce',
 'water_1.5L',
 'winebottle_mid',
 'beer_dom',
 'beer_imp',
 'cigarettes_20']